name: EnterLuck
favicon: null
layout_spectrum: 0.61636
typography_spectrum: 0.5004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1fca69'
    - '#1e1e1e'
    - '#949494'
    - '#555555'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.7271300812717527
  rhythmicContrast: 0.8491848115809262
purpose: []
